//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.12 at 12:37:16 AM BRST 
//


package br.com.nascisoft.apoioterritoriols.admin.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mapas" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}MapasType" minOccurs="0"/>
 *         &lt;element name="surdos" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}SurdosType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackupType", propOrder = {
    "mapas",
    "surdos"
})
@XmlRootElement(name="backup")
public class BackupType {

    protected MapasType mapas;
    protected SurdosType surdos;

    /**
     * Gets the value of the mapas property.
     * 
     * @return
     *     possible object is
     *     {@link MapasType }
     *     
     */
    public MapasType getMapas() {
        return mapas;
    }

    /**
     * Sets the value of the mapas property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapasType }
     *     
     */
    public void setMapas(MapasType value) {
        this.mapas = value;
    }

    /**
     * Gets the value of the surdos property.
     * 
     * @return
     *     possible object is
     *     {@link SurdosType }
     *     
     */
    public SurdosType getSurdos() {
        return surdos;
    }

    /**
     * Sets the value of the surdos property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurdosType }
     *     
     */
    public void setSurdos(SurdosType value) {
        this.surdos = value;
    }

}
