//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.22 at 03:52:06 PM BRT 
//


package br.com.nascisoft.apoioterritoriols.admin.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BackupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BackupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usuarios" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}UsuariosType" minOccurs="0"/>
 *         &lt;element name="cidades" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}CidadesType"/>
 *         &lt;element name="regioes" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}RegioesType"/>
 *         &lt;element name="mapas" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}MapasType" minOccurs="0"/>
 *         &lt;element name="bairros" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}BairrosType" minOccurs="0"/>
 *         &lt;element name="surdos" type="{http://www.nascisoft.com.br/apoioterritoriols/admin/xml}SurdosType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BackupType", propOrder = {
    "usuarios",
    "cidades",
    "regioes",
    "mapas",
    "bairros",
    "surdos"
})
public class BackupType {

    protected UsuariosType usuarios;
    @XmlElement(required = true)
    protected CidadesType cidades;
    @XmlElement(required = true)
    protected RegioesType regioes;
    protected MapasType mapas;
    protected BairrosType bairros;
    protected SurdosType surdos;

    /**
     * Gets the value of the usuarios property.
     * 
     * @return
     *     possible object is
     *     {@link UsuariosType }
     *     
     */
    public UsuariosType getUsuarios() {
        return usuarios;
    }

    /**
     * Sets the value of the usuarios property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsuariosType }
     *     
     */
    public void setUsuarios(UsuariosType value) {
        this.usuarios = value;
    }

    /**
     * Gets the value of the cidades property.
     * 
     * @return
     *     possible object is
     *     {@link CidadesType }
     *     
     */
    public CidadesType getCidades() {
        return cidades;
    }

    /**
     * Sets the value of the cidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link CidadesType }
     *     
     */
    public void setCidades(CidadesType value) {
        this.cidades = value;
    }

    /**
     * Gets the value of the regioes property.
     * 
     * @return
     *     possible object is
     *     {@link RegioesType }
     *     
     */
    public RegioesType getRegioes() {
        return regioes;
    }

    /**
     * Sets the value of the regioes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegioesType }
     *     
     */
    public void setRegioes(RegioesType value) {
        this.regioes = value;
    }

    /**
     * Gets the value of the mapas property.
     * 
     * @return
     *     possible object is
     *     {@link MapasType }
     *     
     */
    public MapasType getMapas() {
        return mapas;
    }

    /**
     * Sets the value of the mapas property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapasType }
     *     
     */
    public void setMapas(MapasType value) {
        this.mapas = value;
    }

    /**
     * Gets the value of the bairros property.
     * 
     * @return
     *     possible object is
     *     {@link BairrosType }
     *     
     */
    public BairrosType getBairros() {
        return bairros;
    }

    /**
     * Sets the value of the bairros property.
     * 
     * @param value
     *     allowed object is
     *     {@link BairrosType }
     *     
     */
    public void setBairros(BairrosType value) {
        this.bairros = value;
    }

    /**
     * Gets the value of the surdos property.
     * 
     * @return
     *     possible object is
     *     {@link SurdosType }
     *     
     */
    public SurdosType getSurdos() {
        return surdos;
    }

    /**
     * Sets the value of the surdos property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurdosType }
     *     
     */
    public void setSurdos(SurdosType value) {
        this.surdos = value;
    }

}
