//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.23 at 10:56:56 AM BRST 
//


package br.com.nascisoft.apoioterritoriols.admin.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CidadeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CidadeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitudeCentro" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitudeCentro" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="latitudeCentroTerritorio" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitudeCentroTerritorio" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="quantidadeSurdosMapa" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="utilizarBairroBuscaEndereco" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pais" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CidadeType", propOrder = {
    "identificador",
    "nome",
    "latitudeCentro",
    "longitudeCentro",
    "latitudeCentroTerritorio",
    "longitudeCentroTerritorio",
    "quantidadeSurdosMapa",
    "utilizarBairroBuscaEndereco",
    "uf",
    "pais"
})
public class CidadeType {

    protected long identificador;
    @XmlElement(required = true)
    protected String nome;
    protected double latitudeCentro;
    protected double longitudeCentro;
    protected double latitudeCentroTerritorio;
    protected double longitudeCentroTerritorio;
    protected int quantidadeSurdosMapa;
    protected boolean utilizarBairroBuscaEndereco;
    @XmlElement(name = "UF", required = true)
    protected String uf;
    @XmlElement(required = true)
    protected String pais;

    /**
     * Gets the value of the identificador property.
     * 
     */
    public long getIdentificador() {
        return identificador;
    }

    /**
     * Sets the value of the identificador property.
     * 
     */
    public void setIdentificador(long value) {
        this.identificador = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the latitudeCentro property.
     * 
     */
    public double getLatitudeCentro() {
        return latitudeCentro;
    }

    /**
     * Sets the value of the latitudeCentro property.
     * 
     */
    public void setLatitudeCentro(double value) {
        this.latitudeCentro = value;
    }

    /**
     * Gets the value of the longitudeCentro property.
     * 
     */
    public double getLongitudeCentro() {
        return longitudeCentro;
    }

    /**
     * Sets the value of the longitudeCentro property.
     * 
     */
    public void setLongitudeCentro(double value) {
        this.longitudeCentro = value;
    }

    /**
     * Gets the value of the latitudeCentroTerritorio property.
     * 
     */
    public double getLatitudeCentroTerritorio() {
        return latitudeCentroTerritorio;
    }

    /**
     * Sets the value of the latitudeCentroTerritorio property.
     * 
     */
    public void setLatitudeCentroTerritorio(double value) {
        this.latitudeCentroTerritorio = value;
    }

    /**
     * Gets the value of the longitudeCentroTerritorio property.
     * 
     */
    public double getLongitudeCentroTerritorio() {
        return longitudeCentroTerritorio;
    }

    /**
     * Sets the value of the longitudeCentroTerritorio property.
     * 
     */
    public void setLongitudeCentroTerritorio(double value) {
        this.longitudeCentroTerritorio = value;
    }

    /**
     * Gets the value of the quantidadeSurdosMapa property.
     * 
     */
    public int getQuantidadeSurdosMapa() {
        return quantidadeSurdosMapa;
    }

    /**
     * Sets the value of the quantidadeSurdosMapa property.
     * 
     */
    public void setQuantidadeSurdosMapa(int value) {
        this.quantidadeSurdosMapa = value;
    }

    /**
     * Gets the value of the utilizarBairroBuscaEndereco property.
     * 
     */
    public boolean isUtilizarBairroBuscaEndereco() {
        return utilizarBairroBuscaEndereco;
    }

    /**
     * Sets the value of the utilizarBairroBuscaEndereco property.
     * 
     */
    public void setUtilizarBairroBuscaEndereco(boolean value) {
        this.utilizarBairroBuscaEndereco = value;
    }

    /**
     * Gets the value of the uf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUF() {
        return uf;
    }

    /**
     * Sets the value of the uf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUF(String value) {
        this.uf = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

}
