//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.22 at 03:52:06 PM BRT 
//


package br.com.nascisoft.apoioterritoriols.admin.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.nascisoft.apoioterritoriols.admin.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Backup_QNAME = new QName("http://www.nascisoft.com.br/apoioterritoriols/admin/xml", "backup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.nascisoft.apoioterritoriols.admin.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BackupType }
     * 
     */
    public BackupType createBackupType() {
        return new BackupType();
    }

    /**
     * Create an instance of {@link UsuariosType }
     * 
     */
    public UsuariosType createUsuariosType() {
        return new UsuariosType();
    }

    /**
     * Create an instance of {@link MapaType }
     * 
     */
    public MapaType createMapaType() {
        return new MapaType();
    }

    /**
     * Create an instance of {@link MapasType }
     * 
     */
    public MapasType createMapasType() {
        return new MapasType();
    }

    /**
     * Create an instance of {@link MelhorPeriodoType }
     * 
     */
    public MelhorPeriodoType createMelhorPeriodoType() {
        return new MelhorPeriodoType();
    }

    /**
     * Create an instance of {@link SurdoType }
     * 
     */
    public SurdoType createSurdoType() {
        return new SurdoType();
    }

    /**
     * Create an instance of {@link BairroType }
     * 
     */
    public BairroType createBairroType() {
        return new BairroType();
    }

    /**
     * Create an instance of {@link RegiaoType }
     * 
     */
    public RegiaoType createRegiaoType() {
        return new RegiaoType();
    }

    /**
     * Create an instance of {@link BairrosType }
     * 
     */
    public BairrosType createBairrosType() {
        return new BairrosType();
    }

    /**
     * Create an instance of {@link SurdosType }
     * 
     */
    public SurdosType createSurdosType() {
        return new SurdosType();
    }

    /**
     * Create an instance of {@link RegioesType }
     * 
     */
    public RegioesType createRegioesType() {
        return new RegioesType();
    }

    /**
     * Create an instance of {@link CidadesType }
     * 
     */
    public CidadesType createCidadesType() {
        return new CidadesType();
    }

    /**
     * Create an instance of {@link MelhorDiaType }
     * 
     */
    public MelhorDiaType createMelhorDiaType() {
        return new MelhorDiaType();
    }

    /**
     * Create an instance of {@link UsuarioType }
     * 
     */
    public UsuarioType createUsuarioType() {
        return new UsuarioType();
    }

    /**
     * Create an instance of {@link CidadeType }
     * 
     */
    public CidadeType createCidadeType() {
        return new CidadeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BackupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nascisoft.com.br/apoioterritoriols/admin/xml", name = "backup")
    public JAXBElement<BackupType> createBackup(BackupType value) {
        return new JAXBElement<BackupType>(_Backup_QNAME, BackupType.class, null, value);
    }

}
