//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.23 at 10:56:56 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nascisoft.com.br/apoioterritoriols/admin/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.nascisoft.apoioterritoriols.admin.xml;
