//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.22 at 03:52:06 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nascisoft.com.br/apoioterritoriols/admin/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.nascisoft.apoioterritoriols.admin.xml;
