//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.12 at 12:37:16 AM BRST 
//


package br.com.nascisoft.apoioterritoriols.admin.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SurdoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SurdoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="regiao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logradouro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="complemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bairro" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cep" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="observacao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="libras" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="crianca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dvd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="instrutor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sexo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="horario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="melhorDia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="onibus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mapa" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="estaAssociadoMapa" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="msn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="possuiMSN" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="mudouSe" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="visitarSomentePorAnciaos" type="{http://www.w3.org/2001/XMLSchema}boolean"/>        
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurdoType", propOrder = {
    "id",
    "regiao",
    "nome",
    "logradouro",
    "numero",
    "complemento",
    "bairro",
    "cep",
    "observacao",
    "telefone",
    "libras",
    "crianca",
    "dvd",
    "instrutor",
    "idade",
    "sexo",
    "horario",
    "melhorDia",
    "onibus",
    "mapa",
    "estaAssociadoMapa",
    "msn",
    "possuiMSN",
    "latitude",
    "longitude",
    "mudouSe",
    "visitarSomentePorAnciaos"
})
public class SurdoType {

    protected long id;
    @XmlElement(required = true)
    protected String regiao;
    @XmlElement(required = true)
    protected String nome;
    @XmlElement(required = true)
    protected String logradouro;
    @XmlElement(required = true)
    protected String numero;
    protected String complemento;
    protected String bairro;
    protected String cep;
    protected String observacao;
    protected String telefone;
    protected String libras;
    protected String crianca;
    protected String dvd;
    protected String instrutor;
    protected String idade;
    protected String sexo;
    protected String horario;
    protected String melhorDia;
    protected String onibus;
    protected Long mapa;
    protected boolean estaAssociadoMapa;
    protected String msn;
    protected boolean possuiMSN;
    protected double latitude;
    protected double longitude;
    protected boolean mudouSe;
    protected boolean visitarSomentePorAnciaos;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the regiao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegiao() {
        return regiao;
    }

    /**
     * Sets the value of the regiao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegiao(String value) {
        this.regiao = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the logradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogradouro() {
        return logradouro;
    }

    /**
     * Sets the value of the logradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogradouro(String value) {
        this.logradouro = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the complemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplemento() {
        return complemento;
    }

    /**
     * Sets the value of the complemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplemento(String value) {
        this.complemento = value;
    }

    /**
     * Gets the value of the bairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * Sets the value of the bairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBairro(String value) {
        this.bairro = value;
    }

    /**
     * Gets the value of the cep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCep() {
        return cep;
    }

    /**
     * Sets the value of the cep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCep(String value) {
        this.cep = value;
    }

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacao() {
        return observacao;
    }

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacao(String value) {
        this.observacao = value;
    }

    /**
     * Gets the value of the telefone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefone() {
        return telefone;
    }

    /**
     * Sets the value of the telefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefone(String value) {
        this.telefone = value;
    }

    /**
     * Gets the value of the libras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibras() {
        return libras;
    }

    /**
     * Sets the value of the libras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibras(String value) {
        this.libras = value;
    }

    /**
     * Gets the value of the crianca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrianca() {
        return crianca;
    }

    /**
     * Sets the value of the crianca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrianca(String value) {
        this.crianca = value;
    }

    /**
     * Gets the value of the dvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvd() {
        return dvd;
    }

    /**
     * Sets the value of the dvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvd(String value) {
        this.dvd = value;
    }

    /**
     * Gets the value of the instrutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrutor() {
        return instrutor;
    }

    /**
     * Sets the value of the instrutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrutor(String value) {
        this.instrutor = value;
    }

    /**
     * Gets the value of the idade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdade() {
        return idade;
    }

    /**
     * Sets the value of the idade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdade(String value) {
        this.idade = value;
    }

    /**
     * Gets the value of the sexo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * Sets the value of the sexo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSexo(String value) {
        this.sexo = value;
    }

    /**
     * Gets the value of the horario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorario() {
        return horario;
    }

    /**
     * Sets the value of the horario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorario(String value) {
        this.horario = value;
    }

    /**
     * Gets the value of the melhorDia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMelhorDia() {
        return melhorDia;
    }

    /**
     * Sets the value of the melhorDia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMelhorDia(String value) {
        this.melhorDia = value;
    }

    /**
     * Gets the value of the onibus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnibus() {
        return onibus;
    }

    /**
     * Sets the value of the onibus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnibus(String value) {
        this.onibus = value;
    }

    /**
     * Gets the value of the mapa property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMapa() {
        return mapa;
    }

    /**
     * Sets the value of the mapa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMapa(Long value) {
        this.mapa = value;
    }

    /**
     * Gets the value of the estaAssociadoMapa property.
     * 
     */
    public boolean isEstaAssociadoMapa() {
        return estaAssociadoMapa;
    }

    /**
     * Sets the value of the estaAssociadoMapa property.
     * 
     */
    public void setEstaAssociadoMapa(boolean value) {
        this.estaAssociadoMapa = value;
    }

    /**
     * Gets the value of the msn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsn() {
        return msn;
    }

    /**
     * Sets the value of the msn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsn(String value) {
        this.msn = value;
    }

    /**
     * Gets the value of the possuiMSN property.
     * 
     */
    public boolean isPossuiMSN() {
        return possuiMSN;
    }

    /**
     * Sets the value of the possuiMSN property.
     * 
     */
    public void setPossuiMSN(boolean value) {
        this.possuiMSN = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the possuiMSN property.
     * 
     */
    public boolean isMudouSe() {
        return mudouSe;
    }

    /**
     * Sets the value of the possuiMSN property.
     * 
     */
    public void setMudouSe(boolean value) {
        this.mudouSe = value;
    }
    
    /**
     * Gets the value of the possuiMSN property.
     * 
     */
    public boolean isVisitarSomentePorAnciaos() {
        return visitarSomentePorAnciaos;
    }

    /**
     * Sets the value of the possuiMSN property.
     * 
     */
    public void setVisitarSomentePorAnciaos(boolean value) {
        this.visitarSomentePorAnciaos = value;
    }
    
}
